name: project-euler-haskell
version: 0.1.0.0
github: "moniquelive/project-euler-haskell"
license: BSD3
author: "MoniqueLive"
maintainer: "moniquelive@moniquelive.com"
copyright: "Copyleft 2023"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/lccro/project-euler-haskell#readme>

dependencies:
  - base == 4.*
  - primes
  - text
  - hspec
  - time
  - split
  - containers
  - array

ghc-options: -j -Wall -O2 -optc-O3 -optc-ffast-math -funfolding-use-threshold=16 -threaded -rtsopts

library:
  source-dirs: src

executables:
  project-euler-haskell-exe:
    main: Main.hs
    source-dirs: app
    dependencies: project-euler-haskell

tests:
  project-euler-haskell-test:
    defaults: hspec/hspec@main
    dependencies: project-euler-haskell
